# ESSE CONFIG_HELPER SERVE PARA PEGAR O CAMINHO DA BASE DO PROJETO E JOGAR NA VARIAVEL {ROOT} #
# SENDO ASSIM NÃO PRECISAMOS SEMPRE COLOCAR O CAMINHO INTEIROS DAS PASTAS E ARQUIVOS #
import os
from pathlib import Path

ROOT = Path(__file__).parents[2]